### ISSUE TITLE
csv files not updated

### ISSUE THREAD

**Issue by JohnPiepersSmits** [davidmegginson/ourairports-data#1]
Hi,
The csv files are not being updated since December 5th.
Can you look into this?

Regards,
John

**Comment by kontrarie** [comment]
I have already mentioned the issue to David per e-mail - he must be very busy, obviously.

**Comment by gatelli** [comment]
Me too, no answer...

**Comment by JohnPiepersSmits** [comment]
I have sent two emails already, no response. Although David does reply in the comment section of the website.

**Comment by davidmegginson** [comment]
Thanks for letting me know! The push to GitHub was failing. I cleaned
things up and tested, and it seems to be working now.

Cheers, David

--
David MEGGINSON (he/him)

*Mobile:* +1-613-791-8553
*Skype:* david.megginson
*TZ:* Eastern North America (EST, UTC-0500; EDT, UTC-0400)

**Comment by kontrarie** [comment]
Thanks David!

I ran some quick tests, and at least I am seeing modified data files 
now, the first time in almost a full month... I'll keep running my 
normal routines, which include a daily download of your csv's, and will 
keep you posted, either of "working fine" or "working less than fine" ;)

Please accept my warmest wishes for good health, good fortune, and 
joyful work in 2022!

Very kindly yours,

Karel A.J. ADAMS

**Comment by kontrarie** [comment]
Looks like being ok now.

**Comment by gatelli** [comment]
Good news ! Many thanks !

**Comment by JohnPiepersSmits** [comment]
Seems to be working for me!
Thanks!
