### ISSUE TITLE
Open mySQL database

### ISSUE THREAD

**Issue by Fifcok** [davidmegginson/ourairports-data#10]
Will you create mySQL database? I import your *.csv files to my database, but I see that there are still updates, or is there any way to automatically import *.csv files automatically from github to my database when there will be change in files?

**Comment by davidmegginson** [comment]
The actual OurAirports database is normalised and much more complex. The CSV files are from simplified views that join multiple tables.

If you want to create some basic database tables directly from them, the numerical IDs do not change, so you can use those as primary keys. MySQL has an ON DUPLICATE KEY UPDATE modifier for INSERT, which will let you keep reimporting the CSV data without breaking any existing links in your database (you might also want to set up a way to deal with deletions, though). Best of luck!
