### ISSUE TITLE
Any plans to publish these datasets as packages?

### ISSUE THREAD

**Issue by milsosa** [davidmegginson/ourairports-data#17]
I consider that for many using these datasets, it will be beneficial to have them published as packages that can be installed through the corresponding dependency managers of the programming language they are using, for example, npm package for Node.js.

I am sure the Open Source community could support on automating the publishing of such packages.

One of the benefits of having these as published packages is that keeping the services using them up-to-date will become easier.

**Comment by bennycode** [comment]
@davidmegginson any updates on this? It would help immsenly to have your data published in a registry like [GitHub Packages registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry) or [npm](https://www.npmjs.com/).

**Comment by davidmegginson** [comment]
Given that the datasets update daily and have perma-URLs, I'm not sure that I see the advantage of adding an extra layer of indirection to using them. That said, I have no objection if anyone wants to package them up for a specific framework.
