### ISSUE TITLE
Any way to fetch the closest metar weather station for a small airport

### ISSUE THREAD

**Issue by zknox72** [davidmegginson/ourairports-data#20]
Hello, Can I get some advice to find the nearest weather station to a private airport. Is that information in any of the csvs available in this repo. If not, what is the best place to find it myself? Thank you

**Comment by kontrarie** [comment]
Not really. This database collects and shares information about aerodromes, no less, no more. Dear old David seems to have his hands more than full at keeping the present functionality up and running, it is not kind to request more from him after he already did and does so much.
The required functionality will rather be vailable from flight planning tools, online or not. Which is best will depend much on the area, I don't think any exists that covers Ireland as well as Chili - just to name two example countries, of course.

**Comment by zknox72** [comment]
Thank you for the info!
