### ISSUE TITLE
ISO Region Zabaykalsky Krai ZBA instead of CHI.

### ISSUE THREAD

**Issue by lxndrb22** [davidmegginson/ourairports-data#27]
Hello David
First I would like to thank you once again here, for maintaing this excelent resource 'ourairports.com'! 
Regarding The ISO Region for Zabaykalsky Krai:
To be in line with the ISO specification, it should be coded ZBA instead of CHI.
Kind regards
Alexander

**Comment by davidmegginson** [comment]
Thank you very much.  I've changed the ISO 3166-2 code to "ZAB".  You can see it online now, and it should show up in tomorrow's data dump on GitHub.
