### ISSUE TITLE
Missing Region of Chile in regions.csv

### ISSUE THREAD

**Issue by benyamins** [davidmegginson/ourairports-data#28]
Hello David! I noticed that a region of Chile is missing, and because of that, some airports have an incorrect region assigned.

An example of this problem is [El Litral airport](https://ourairports.com/airports/SCUL/) which should have "CL-NB" as a region, ie [Ñuble](https://en.wikipedia.org/wiki/ISO_3166-2:CL).

In the english Wikipedia, the data is incorrect, while the spanish one has [the correct info](https://es.wikipedia.org/wiki/Aer%C3%B3dromo_El_Litral).

Thanks for the work you've done.
Kind regards,
Benjamin

**Comment by davidmegginson** [comment]
Thanks for the report!  I see that @Bill35 fixed the problem before I made
it to your message, and I hope all is well now.

https://ourairports.com/countries/CL/NB/


Cheers, David

--
David MEGGINSON (he/him)

*Mobile:* +1-613-791-8553
*Skype:* david.megginson
*TZ:* Eastern North America (EST, UTC-0500; EDT, UTC-0400)

**Comment by benyamins** [comment]
Thanks a lot Bill and David!
