### ISSUE TITLE
Airport's tax and fee codes

### ISSUE THREAD

**Issue by lyvietanh** [davidmegginson/ourairports-data#29]
I found some metadata information for identifier code of taxes and fees.
How do you think you can add a new data file of them? 
Thanks.

Refer to direct URL:
https://www.singaporeair.com/flightsearch/passengerDetail.form (search keyword: **taxes**)
https://booking.vietnamairlines.com/statics/applications/booking/dynamicContent/1.0.83/en-GB.json (search keyword: **global.taxes**)

**Comment by davidmegginson** [comment]
It's an interesting idea, but I don't think it will make the next few rounds of updates.

What you could do is add your own tags to airports for different taxes and fees.  I could include user tags in the CSV output without too much difficulty.
