### ISSUE TITLE
Process for adding new airports - UKBD

### ISSUE THREAD

**Issue by cliftonlabrum** [davidmegginson/ourairports-data#5]
I'm so glad this is all on GitHub now. 😄🎉

Do you have a recommended process for adding new airports? One of my app's users reported that `UKBD` is missing: https://www.airmate.aero/php/airport_page.php?page=airport_page&code=UKBD

I could add it and create a pull request, but I'm not sure how to handle the `id` (first column in **airports.csv**).

**Comment by kontrarie** [comment]
* for adding a new aerodrome, surf to the ourairports.com website and set up your account there; you can then add and modify fields; be aware that David uses github only as a medium for publication of the csv dumps;
* the field you mentioned was already present, only its ICAO code was missing, I have added it now, you should see it in the next extraction, due in a couple of hours;
* beware of Ukraine in several senses: it is today not a safe place to go flying your private plane, and tensions with Russia are high, very high. For one example, the field mentioned is called Ksaverovka in Russian, and that's what your reference site copied, but in local Ukrainian it is Ksaverivka
*
Hoping this helps,
